# Generated by Django 6.0.6 on 2026-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='门店名称')),
                ('description', models.TextField(blank=True, verbose_name='门店描述')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='详细地址')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('business_hours', models.JSONField(blank=True, default=dict, verbose_name='营业时间')),
                ('status', models.CharField(choices=[('open', '营业中'), ('closed', '已关闭'), ('paused', '暂停营业')], db_index=True, default='open', max_length=20, verbose_name='运营状态')),
                ('cover_image', models.URLField(blank=True, max_length=512, verbose_name='封面图 URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店列表',
                'db_table': 'store',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
