# Generated by Django 6.0.6 on 2026-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='门店编码/机身注册码'),
        ),
    ]
