# Generated by Django 6.0.6 on 2026-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='门店注册码'),
        ),
    ]
