# Generated by Django 6.0.6 on 2026-06-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='门店ID'),
        ),
    ]
