services:
  db:
    image: mysql:9.0
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"



  emqx:
    image: emqx:5.8.0
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log



  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./automake/static:/app/static
      - ./automake/media:/app/media
    extra_hosts:
      - "host.docker.internal:host-gateway"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A default worker -l info
    restart: always
    env_file: .env
    environment:
      - MYSQL_HOST=db
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/2
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    volumes:
      - .:/app
    depends_on:
      - db
      - redis



volumes:
  mysql_data:
  emqx_data:
  emqx_log:
  python_packages:
