# Generated by Django 6.0.6 on 2026-06-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(db_index=True, max_length=64, verbose_name='商户订单号')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='微信交易号')),
                ('raw_body', models.TextField(verbose_name='原始回调报文')),
                ('decrypted_data', models.JSONField(blank=True, default=dict, verbose_name='解密后数据')),
                ('process_result', models.CharField(default='pending', max_length=20, verbose_name='处理结果')),
                ('process_error', models.TextField(blank=True, verbose_name='处理错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
            options={
                'verbose_name': '支付回调日志',
                'verbose_name_plural': '支付回调日志',
                'db_table': 'payment_callback_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='微信退款单号')),
                ('out_refund_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='商户退款单号')),
                ('refund_amount', models.IntegerField(verbose_name='退款金额（分）')),
                ('reason', models.CharField(blank=True, max_length=256, verbose_name='退款原因')),
                ('status', models.CharField(choices=[('pending', '申请中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='退款状态')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录列表',
                'db_table': 'refund_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='微信交易号')),
                ('out_trade_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='商户订单号')),
                ('amount', models.IntegerField(verbose_name='支付金额（分）')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('closed', '已关闭')], db_index=True, default='pending', max_length=20, verbose_name='支付状态')),
                ('pay_params', models.JSONField(blank=True, default=dict, verbose_name='支付参数')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('pay_method', models.CharField(default='wechat_jsapi', max_length=32, verbose_name='支付方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='orders.ordermain', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录列表',
                'db_table': 'payment_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
