# Generated by Django 6.0.6 on 2026-06-09 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to=settings.AUTH_USER_MODEL, verbose_name='支付用户'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_records', to='orders.ordermain', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_records', to='payments.paymentrecord', verbose_name='关联支付'),
        ),
    ]
