# Generated by Django 6.0.6 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrecord',
            name='status',
            field=models.CharField(choices=[('pending', '申请中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='退款状态'),
        ),
    ]
