# Generated by Django 6.0.6 on 2026-06-17 05:04

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0005_devicematerialstock'),
        ('orders', '0005_orderitem_skus_ordermain_order_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重告警')], db_index=True, default='info', max_length=10, verbose_name='通知级别')),
                ('event_type', models.CharField(choices=[('order_status', '订单状态'), ('device_alert', '设备告警'), ('material_low', '物料不足'), ('pickup_ready', '取餐就绪'), ('system', '系统事件')], db_index=True, max_length=20, verbose_name='事件类型')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('is_handled', models.BooleanField(db_index=True, default=False, verbose_name='已处理')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发生时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_events', to='devices.device', verbose_name='关联设备')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_notify_events', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_events', to='orders.ordermain', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '通知事件',
                'verbose_name_plural': '通知事件列表',
                'db_table': 'notify_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=notifications.models.generate_pickup_code, max_length=8, unique=True, verbose_name='取餐码')),
                ('status', models.CharField(choices=[('active', '有效'), ('used', '已使用'), ('expired', '已过期')], db_index=True, default='active', max_length=10, verbose_name='状态')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='扫码时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_code', to='orders.ordermain', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '取餐码',
                'verbose_name_plural': '取餐码列表',
                'db_table': 'pickup_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WxSubscribeMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=128, verbose_name='接收者 openid')),
                ('msg_type', models.CharField(choices=[('order_status', '订单状态通知'), ('alert', '告警通知'), ('pickup', '取餐码通知')], db_index=True, max_length=20, verbose_name='消息类型')),
                ('status', models.CharField(choices=[('pending', '等待发送'), ('success', '发送成功'), ('failed', '发送失败'), ('skipped', '已跳过')], db_index=True, default='pending', max_length=20, verbose_name='发送状态')),
                ('template_id', models.CharField(max_length=128, verbose_name='模板 ID')),
                ('data_payload', models.JSONField(default=dict, verbose_name='消息数据')),
                ('wx_errcode', models.IntegerField(blank=True, null=True, verbose_name='微信错误码')),
                ('wx_errmsg', models.CharField(blank=True, max_length=256, verbose_name='微信错误信息')),
                ('celery_task_id', models.CharField(blank=True, max_length=64, verbose_name='Celery 任务 ID')),
                ('retry_count', models.SmallIntegerField(default=0, verbose_name='重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='成功发送时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wx_msgs', to='orders.ordermain', verbose_name='关联订单')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wx_subscribe_msgs', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '微信订阅消息',
                'verbose_name_plural': '微信订阅消息列表',
                'db_table': 'wx_subscribe_msg',
                'ordering': ['-created_at'],
            },
        ),
    ]
