# Generated by Django 6.0.6 on 2026-09-10 19:41

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyevent',
            name='event_type',
            field=models.CharField(choices=[('order_status', '订单状态'), ('device_alert', '设备告警'), ('material_low', '物料不足'), ('material_expiring', '物料保质期预警'), ('pickup_ready', '取餐就绪'), ('system', '系统事件')], db_index=True, max_length=20, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='pickupcode',
            name='code',
            field=models.CharField(db_index=True, default=notifications.models.generate_pickup_code, max_length=16, verbose_name='取餐码'),
        ),
    ]
