# Generated by Django 6.0.6 on 2026-06-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('icon_url', models.URLField(blank=True, max_length=512, verbose_name='分类图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='stores.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '菜单分类',
                'verbose_name_plural': '菜单分类列表',
                'db_table': 'menu_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('image_url', models.URLField(blank=True, max_length=512, verbose_name='商品图片')),
                ('base_price', models.IntegerField(default=0, verbose_name='基础价格（分）')),
                ('stock_type', models.CharField(choices=[('device', '设备管理'), ('manual', '手动管理'), ('unlimited', '不限库存')], default='device', max_length=20, verbose_name='库存类型')),
                ('manual_stock', models.IntegerField(default=0, verbose_name='手动库存数量')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menucategory', verbose_name='分类')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='stores.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '菜单商品',
                'verbose_name_plural': '菜单商品列表',
                'db_table': 'menu_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='规格名称')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='规格属性')),
                ('price_delta', models.IntegerField(default=0, verbose_name='价格增量（分）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='menus.menuitem', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格列表',
                'db_table': 'menu_sku',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=64, verbose_name='物料名称')),
                ('material_code', models.CharField(db_index=True, max_length=64, verbose_name='物料编码')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前库存量')),
                ('unit', models.CharField(default='ml', max_length=16, verbose_name='单位')),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='告警阈值')),
                ('last_reported_at', models.DateTimeField(blank=True, null=True, verbose_name='最后上报时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_stocks', to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '物料库存',
                'verbose_name_plural': '物料库存列表',
                'db_table': 'material_stock',
                'unique_together': {('device', 'material_code')},
            },
        ),
    ]
