# Generated by Django 6.0.6 on 2026-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstock',
            name='locked_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='锁定库存量'),
        ),
    ]
