# Generated by Django 6.0.6 on 2026-06-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_materialstock_locked_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='manual_stock',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='stock_type',
        ),
    ]
