# Generated by Django 6.0.6 on 2026-06-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_menuitem_manual_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='icon_url',
            field=models.FileField(blank=True, max_length=512, upload_to='category_icons/', verbose_name='分类图标'),
        ),
    ]
