# Generated by Django 6.0.6 on 2026-06-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0001_initial'),
        ('menus', '0004_alter_menucategory_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='global_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_categories', to='global_config.globalmenucategory', verbose_name='继承的全局分类'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='global_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_items', to='global_config.globalmenuitem', verbose_name='继承的全局商品'),
        ),
        migrations.AddField(
            model_name='menusku',
            name='global_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_skus', to='global_config.globalmenusku', verbose_name='继承的全局SKU'),
        ),
    ]
