# Generated by Django 6.0.6 on 2026-06-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0001_initial'),
        ('menus', '0005_menucategory_global_category_menuitem_global_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='global_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='local_categories', to='global_config.globalmenucategory', verbose_name='继承的全局分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='global_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='local_items', to='global_config.globalmenuitem', verbose_name='继承的全局商品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menusku',
            name='global_sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='local_skus', to='global_config.globalmenusku', verbose_name='继承的全局SKU'),
            preserve_default=False,
        ),
    ]
