# Generated by Django 6.0.6 on 2026-06-11 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0001_initial'),
        ('menus', '0006_alter_menucategory_global_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='global_category',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='store',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menusku',
            name='global_sku',
        ),
        migrations.RemoveField(
            model_name='menusku',
            name='item',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='device_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='local_items', to='global_config.devicetype', verbose_name='设备类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='base_price',
            field=models.IntegerField(verbose_name='基础价格（分）'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='global_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_items', to='global_config.globalmenuitem', verbose_name='全局商品'),
        ),
        migrations.DeleteModel(
            name='MaterialStock',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
