# Generated by Django 6.0.6 on 2026-06-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_remove_menucategory_global_category_and_more'),
        ('orders', '0003_alter_orderitem_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuSku',
        ),
    ]
