# Generated by Django 6.0.6 on 2026-06-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0001_initial'),
        ('menus', '0008_delete_menusku'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_delta', models.IntegerField(default=0, verbose_name='价格增量（分）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('global_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_skus', to='global_config.globalmenusku', verbose_name='继承的全局SKU')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='menus.menuitem', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格列表',
                'db_table': 'menu_sku',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
