# Generated by Django 6.0.6 on 2026-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_menusku'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusku',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='分类'),
        ),
    ]
