# Generated by Django 6.0.6 on 2026-06-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_menusku_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusku',
            name='category',
        ),
    ]
