# Generated by Django 6.0.6 on 2026-06-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_age_userprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '门店管理员'), ('customer', '客户')], db_index=True, default='customer', max_length=20, verbose_name='角色'),
        ),
    ]
