# Generated by Django 6.0.6 on 2026-06-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_id'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store',
        ),
        migrations.AddField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='admins', to='stores.store', verbose_name='关联门店'),
        ),
    ]
