# Generated by Django 6.0.6 on 2026-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_store_user_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '门店管理员'), ('material_admin', '物料员'), ('customer', '客户')], db_index=True, default='customer', max_length=20, verbose_name='角色'),
        ),
    ]
