# Generated by Django 6.0.6 on 2026-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('admin', '门店管理员'), ('material_admin', '物料员'), ('coordinator', '协调员'), ('guide', '引导员'), ('customer', '客户')], db_index=True, default='customer', max_length=20, verbose_name='角色'),
        ),
    ]
