"""
Django settings for default project.

Generated by 'django-admin startproject' using Django 6.0.6.

本项目使用 .env 文件管理敏感配置，生产环境请勿将 .env 提交到版本库。
"""

import os
from pathlib import Path

# ============================================================
# 基础路径配置
# ============================================================
# 项目根目录（manage.py 所在目录）
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 文件中的环境变量（优先使用系统环境变量，不覆盖已有值）
# 需要安装 python-dotenv：pip install python-dotenv
try:
    from dotenv import load_dotenv
    # 从项目根目录的上一级（docker-compose.yml 所在目录）加载 .env
    load_dotenv(BASE_DIR.parent / '.env')
except ImportError:
    pass  # 若未安装 python-dotenv，依赖系统环境变量

# ============================================================
# MySQL 驱动配置 —— 使用 PyMySQL 替代 mysqlclient（无需 C 编译依赖）
# 通过猴子补丁让 Django 的 mysql 后端识别 PyMySQL
# ============================================================
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass  # 若已安装 mysqlclient 则不需要此补丁


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ============================================================
# 安全配置 —— 所有敏感值必须从环境变量读取，绝不硬编码
# ============================================================

# Django 签名密钥，生产环境必须设置为随机长字符串
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-in-production')

# 调试模式，生产环境必须设为 False
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')
# DEBUG = False
# 允许访问的域名，生产环境应填写实际域名，避免使用通配符
# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*,').split(',')
ALLOWED_HOSTS = ['*']

# 信任的源，用于支持反向代理下的 CSRF 验证
CSRF_TRUSTED_ORIGINS = [
    'https://tinylab.store',
    'http://tinylab.store',
]

# 识别 HTTPS 反向代理的 Header 头，确保 CSRF 和 Cookie 安全校验正确
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'unfold',                           # Unfold 美化后台管理 (必须放在 admin 之前)
    'daphne',                           # Daphne：ASGI 服务器（必须在 staticfiles 之前）
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方库
    'rest_framework',                   # Django REST Framework
    'rest_framework_simplejwt',         # JWT 认证
    'drf_spectacular',                  # OpenAPI 3.0 接口文档生成
    'channels',                         # Django Channels：WebSocket 支持
    # 业务应用
    'global_config',                    # 全局控制与定义
    'users',                            # 用户、权限
    'stores',                           # 门店
    'menus',                            # 菜单
    'orders',                           # 订单
    'payments',                         # 支付
    'devices',                          # 设备
    'simulator',                        # 上位机通信模拟器
    'notifications',                    # 消息通知（微信订阅消息、取餐码、告警）
    'inventory',                        # 物料仓库与进销存管理
    'monitor',                          # 设备监控与分析模块
]

# ============================================================
# Django REST Framework 配置
# ============================================================
REST_FRAMEWORK = {
    # 全局默认认证方式：JWT Bearer Token，开发环境支持免 Token 自动登录和 Session 登录
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'users.authentication.DevMockAuthentication',            # 开发免 Token 自动登录
        'rest_framework.authentication.SessionAuthentication',    # 支持 Session（登录 Admin 后可自动授权）
    ),
    # 默认权限：需登录（可在具体接口覆盖）
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 统一响应格式由自定义 Renderer 控制（后续扩展）
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # 接口文档 Schema 生成器
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ============================================================
# OpenAPI / Swagger (drf-spectacular) 配置
# ============================================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'AutoMake 智能制造系统 API 接口文档',
    'DESCRIPTION': '本项目作为服务器端，提供用户/门店/菜单/订单/支付相关管理接口，以及上位机/设备的 HTTPS POST 注册接口。',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # 默认展示 Swagger UI
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'defaultModelRendering': 'model',
        'displayRequestDuration': True,
    },
}

# ============================================================
# JWT Token 配置
# ============================================================
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),     # Access Token 有效期 2 小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),    # Refresh Token 有效期 30 天
    'ROTATE_REFRESH_TOKENS': True,                   # 刷新时同步更新 Refresh Token
    'BLACKLIST_AFTER_ROTATION': False,               # 暂不启用黑名单
    'AUTH_HEADER_TYPES': ('Bearer',),                # Header 格式：Authorization: Bearer <token>
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'default.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'default.wsgi.application'

# ============================================================
# ASGI / WebSocket 配置（Django Channels）
# ============================================================
# 指定 ASGI 应用入口（替代 WSGI，支持 HTTP + WebSocket 双协议）
ASGI_APPLICATION = 'default.asgi.application'

# Channel Layer 配置：使用 Redis 作为消息后端（db=3，避免与缓存/Celery 冲突）
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [{
                # Redis URL（db=3 专用于 WebSocket Channel Layer）
                'address': os.environ.get('REDIS_WS_URL', 'redis://127.0.0.1:6379/3'),
                # 禁用读超时：channels_redis 使用 Pub/Sub 长连接，必须设为 None
                # 否则空闲超过 socket_timeout 秒后会抛出 TimeoutError
                'socket_timeout': None,
                # 连接建立超时（秒）
                'socket_connect_timeout': 5,
                # TCP Keepalive，防止 NAT/防火墙切断空闲 TCP 连接
                'socket_keepalive': True,
            }],
            # 单个 Channel Group 最大消息容量
            'capacity': 1000,
            # 消息过期时间（秒）
            'expiry': 60,
        },
    },
}


# ============================================================
# 数据库配置 —— MySQL
# 对应 docker-compose.yml 中的 db 服务（mysql:9.0）
# 需要安装驱动：pip install mysqlclient  或  pip install PyMySQL
# ============================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # 使用 MySQL 后端
        'NAME': os.environ.get('MYSQL_DATABASE', 'automake'),          # 数据库名
        'USER': os.environ.get('MYSQL_USER', 'django_user'),           # 数据库用户
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),              # 数据库密码
        'HOST': os.environ.get('MYSQL_HOST', '127.0.0.1'),             # 主机（Docker 映射到本机 3306）
        'PORT': os.environ.get('MYSQL_PORT', '3306'),                  # 端口
        'OPTIONS': {
            'charset': 'utf8mb4',          # 支持 emoji 和完整 Unicode
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 严格模式，防止静默截断
        },
    }
}

# ============================================================
# 缓存配置 —— Redis
# 对应 docker-compose.yml 中的 redis 服务（redis:latest）
# 需要安装：pip install django-redis
# ============================================================
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        # Redis 连接地址：db=1 用于缓存，避免与其他用途冲突
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'TIMEOUT': 3000,  # 默认缓存过期时间（秒）
    }
}

# 使用 Redis 存储 Django Session（可选，提升分布式部署下的 Session 一致性）
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# ============================================================
# 国际化 & 本地化配置
# ============================================================
LANGUAGE_CODE = 'zh-hans'   # 简体中文

TIME_ZONE = 'Asia/Shanghai'  # 中国标准时间（CST，UTC+8）

USE_I18N = True              # 启用国际化翻译

USE_TZ = True                # 使用带时区的 datetime，推荐始终保持 True


# ============================================================
# 静态文件配置
# 对应 docker-compose.yml nginx 服务挂载的 /app/static
# ============================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'   # collectstatic 输出目录

# 媒体文件（用户上传）配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'     # 对应 nginx 挂载的 /app/media

# ============================================================
# 主键类型配置
# ============================================================
# Django 3.2+ 新项目推荐使用 BigAutoField 作为默认主键类型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# 微信小程序配置（从环境变量读取，勿硬编码）
# ============================================================
WECHAT_APP_ID = os.environ.get('WECHAT_APP_ID', '')           # 小程序 AppID
WECHAT_APP_SECRET = os.environ.get('WECHAT_APP_SECRET', '')   # 小程序 AppSecret

# ============================================================
# 微信支付配置（从环境变量读取）
# 证书文件放在项目根目录 cert/ 目录下，不提交到版本库
# ============================================================
WECHAT_PAY_MCH_ID = os.environ.get('WECHAT_PAY_MCH_ID', '')              # 商户号
WECHAT_PAY_API_V3_KEY = os.environ.get('WECHAT_PAY_API_V3_KEY', '')      # APIv3 密钥
WECHAT_PAY_CERT_SERIAL = os.environ.get('WECHAT_PAY_CERT_SERIAL', '')    # 证书序列号
WECHAT_PAY_PRIVATE_KEY_PATH = os.environ.get(                             # 商户私钥文件路径
    'WECHAT_PAY_PRIVATE_KEY_PATH',
    str(BASE_DIR.parent / 'cert' / 'apiClient_key.pem')
)
WECHAT_PAY_NOTIFY_URL = os.environ.get(                                   # 支付回调地址
    'WECHAT_PAY_NOTIFY_URL',
    'https://yourdomain.com/api/pay/callback'
)

# ============================================================
# MQTT / EMQX 配置（对应 docker-compose.yml 中的 emqx 服务）
# ============================================================
MQTT_HOST = os.environ.get('MQTT_HOST', '127.0.0.1')          # EMQX 服务地址
MQTT_PORT = int(os.environ.get('MQTT_PORT', '1883'))          # MQTT 端口
MQTT_USERNAME = os.environ.get('MQTT_USERNAME', '')           # MQTT 用户名
MQTT_PASSWORD = os.environ.get('MQTT_PASSWORD', '')           # MQTT 密码
MQTT_CLIENT_ID = os.environ.get('MQTT_CLIENT_ID', 'django-server-001')  # 客户端 ID

# ============================================================
# 日志配置 (Logging Configuration)
# ============================================================
# 设计原则：
#   1. 【异步写入】所有 handler 挂在 QueueHandler 后，日志写入操作
#      被投递到内存队列，由独立的 QueueListener 线程消费，完全不阻塞请求线程。
#   2. 【按大小切割】每个日志文件上限 500 MB，最多保留 10 个历史片段，
#      自动命名为 xxx.log.1 / xxx.log.2 ... 共约 5 GB 历史空间。
#   3. 【分类存储】业务日志、错误日志、Django 框架日志分别落不同文件，
#      便于运维检索与告警接入。
#   4. 【结构化格式】正式环境建议接入 JSON 格式（已内置 json_verbose），
#      方便后续对接 ELK / Grafana Loki 等日志平台。
# ============================================================

import queue
import logging
import logging.handlers

# 日志目录：项目根目录同级的 logs/ 下（不放在代码目录内，避免误提交）
_LOG_DIR = BASE_DIR.parent / 'logs'
_LOG_DIR.mkdir(parents=True, exist_ok=True)

# 单文件上限 500 MB，保留 10 个滚动片段
_MAX_BYTES  = 500 * 1024 * 1024   # 500 MB
_BACKUP_CNT = 10

# 文件日志统一格式（带时间、级别、模块名、行号）
_file_formatter = logging.Formatter(
    fmt='[%(asctime)s] %(levelname)-8s [%(name)s:%(lineno)d] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
)

def _make_rotating_handler(filename: str, level=logging.DEBUG):
    """工厂：创建一个基于大小切割的 RotatingFileHandler，并绑定统一 formatter"""
    h = logging.handlers.RotatingFileHandler(
        filename=str(_LOG_DIR / filename),
        maxBytes=_MAX_BYTES,
        backupCount=_BACKUP_CNT,
        encoding='utf-8',
    )
    h.setLevel(level)
    h.setFormatter(_file_formatter)   # ← 关键：绑定 formatter
    return h

# ---------- 异步队列 ----------
# 每类日志有独立的内存队列 + QueueListener，互不干扰
_log_queue_app  = queue.Queue(maxsize=5000)   # 业务日志
_log_queue_err  = queue.Queue(maxsize=2000)   # 错误/异常
_log_queue_dj   = queue.Queue(maxsize=2000)   # Django 框架

# 底层实际写入的 Handler（真正落盘的 worker）
#日志级别从低到高依次是 DEBUG < INFO < WARNING < ERROR < CRITICAL。
_file_app  = _make_rotating_handler('app.log',     logging.DEBUG)
_file_err  = _make_rotating_handler('error.log',   logging.ERROR)
_file_dj   = _make_rotating_handler('django.log',  logging.INFO)

# 启动后台监听线程（进程退出时自动 stop）
_listener_app = logging.handlers.QueueListener(_log_queue_app, _file_app, respect_handler_level=True)
_listener_err = logging.handlers.QueueListener(_log_queue_err, _file_err, respect_handler_level=True)
_listener_dj  = logging.handlers.QueueListener(_log_queue_dj,  _file_dj,  respect_handler_level=True)
_listener_app.start()
_listener_err.start()
_listener_dj.start()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # ── 格式器 ──────────────────────────────────────────────
    'formatters': {
        # 普通可读格式（开发 / 控制台）
        'verbose': {
            'format': '[%(asctime)s] %(levelname)-8s [%(name)s:%(lineno)d] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # 结构化 JSON 格式（生产推荐，方便接入 ELK / Loki）
        # 如需启用，将下方 handler 中的 formatter 改为 'json_verbose'
        'json_verbose': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '{\'time\': \'%(asctime)s\', \'level\': \'%(levelname)s\', \'logger\': \'%(name)s\', \'line\': %(lineno)d, \'msg\': %(message)r}',
            'datefmt': '%Y-%m-%dT%H:%M:%S',
        },
    },

    # ── Handler ─────────────────────────────────────────────
    'handlers': {
        # 控制台输出（本地开发用，生产可保留用于 systemd journal）
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'INFO',
        },
        # 【异步】业务日志队列入口（投递到 _log_queue_app）
        'async_app': {
            'class': 'logging.handlers.QueueHandler',
            'queue': _log_queue_app,
        },
        # 【异步】错误日志队列入口（仅 ERROR 及以上）
        'async_err': {
            'class': 'logging.handlers.QueueHandler',
            'queue': _log_queue_err,
        },
        # 【异步】Django 框架日志队列入口
        'async_django': {
            'class': 'logging.handlers.QueueHandler',
            'queue': _log_queue_dj,
        },
    },

    # ── Logger ──────────────────────────────────────────────
    'loggers': {
        # Django 框架日志
        'django': {
            'handlers': ['console', 'async_django'],
            'level': 'INFO',
            'propagate': False,
        },
        # SQL 追踪（仅 WARNING 以上，避免刷屏）
        'django.db.backends': {
            'handlers': ['async_err'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django 请求错误（4xx/5xx）
        'django.request': {
            'handlers': ['console', 'async_err'],
            'level': 'WARNING',
            'propagate': False,
        },
        # ── 业务模块：统一使用 async_app + async_err 双写 ──
        # async_app  → app.log   (DEBUG+)
        # async_err  → error.log (ERROR+)，全局错误收口
        'users':         {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'stores':        {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'menus':         {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'orders':        {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'payments':      {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'devices':       {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'mqtt':          {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'inventory':     {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'notifications': {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'monitor':       {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'global_config': {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
        'utils':         {'handlers': ['console', 'async_app', 'async_err'], 'level': 'DEBUG', 'propagate': False},
    },

    # ── Root Logger（兜底，捕获未列举模块的日志） ──────────
    'root': {
        'handlers': ['console', 'async_app'],
        'level': 'WARNING',
    },
}


# ============================================================
# 自定义用户认证后端
# ============================================================
AUTHENTICATION_BACKENDS = [
    'users.backends.CustomAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ============================================================
# 自定义用户模型（必须在 migrate 前设置好，之后不可轻易更改）
# ============================================================
AUTH_USER_MODEL = 'users.User'

# ============================================================
# Unfold 后台主题与美化配置
# ============================================================
UNFOLD = {
    "SITE_TITLE": "AutoMake 智能制造系统后台",
    "SITE_HEADER": "AutoMake 后台管理",
    # "THEME": "light",  # 若要强制使用浅色主题（并禁用右上角的主题切换按钮），可以取消此行注释。可选值: "light" 或 "dark"
    "DASHBOARD_CALLBACK": "global_config.dashboard.dashboard_callback",
}

# ============================================================
# Celery 异步任务队列配置
# ============================================================
# 消息中间件（Broker）配置，使用 Redis（db=2 避免与其他缓存或 Session 冲突）
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/2')
# 结果存储后端（Result Backend）配置，使用 Redis
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/2')

# 接受的内容格式限制，保证安全
CELERY_ACCEPT_CONTENT = ['json']
# 任务序列化格式
CELERY_TASK_SERIALIZER = 'json'
# 结果序列化格式
CELERY_RESULT_SERIALIZER = 'json'
# 时区配置，与 Django 保持一致
CELERY_TIMEZONE = TIME_ZONE
# 任务结果过期时间，设为 24 小时（防止 Redis 内存膨胀）
CELERY_RESULT_EXPIRES = 86400

# ============================================================
# 微信订阅消息模板 ID 配置
# 在微信公众平台后台申请后填入，不可硬编码（从环境变量读取）
# ============================================================
# 订单状态变更通知模板（发给用户）
WECHAT_TPL_ORDER_STATUS = os.environ.get('WECHAT_TPL_ORDER_STATUS', '')
# 告警通知模板（发给管理员）
WECHAT_TPL_ALERT = os.environ.get('WECHAT_TPL_ALERT', '')
# 取餐码通知模板（发给用户）
WECHAT_TPL_PICKUP = os.environ.get('WECHAT_TPL_PICKUP', '')

# 取餐码有效期（分钟），默认 30 分钟
PICKUP_CODE_EXPIRE_MINUTES = int(os.environ.get('PICKUP_CODE_EXPIRE_MINUTES', '30'))


