# Generated by Django 6.0.6 on 2026-06-20 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0004_alter_store_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='物料编号')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='当前剩余数量')),
                ('unit', models.CharField(help_text='如：kg, 升, 包, 箱', max_length=32, verbose_name='计量单位')),
                ('shelf_life', models.CharField(help_text='如：12个月, 3天', max_length=64, verbose_name='保质期')),
                ('storage_conditions', models.CharField(help_text='如：常温避光, 冷藏(2-8℃), 冷冻', max_length=128, verbose_name='储存条件')),
                ('precautions', models.TextField(blank=True, help_text='安全使用或储存的特殊说明', verbose_name='注意事项')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('retrieve_count', models.IntegerField(default=0, help_text='统计该物料累计出库分拨的次数', verbose_name='取走（出库）次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物料信息',
                'verbose_name_plural': '物料库房',
                'db_table': 'inventory_material',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('in', '进货/入库'), ('out', '出货/出库')], db_index=True, max_length=10, verbose_name='记录类型')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='必须为大于 0 的数值', max_digits=10, verbose_name='变更数量')),
                ('expiration_date', models.DateField(blank=True, help_text='进货时，记录该批物料的具体过期日期', null=True, verbose_name='批次过期时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经办操作员')),
                ('store', models.ForeignKey(blank=True, help_text='仅在“出货/出库”时需要选择对应的门店', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_records', to='stores.store', verbose_name='出库目标门店')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '进出库记录',
                'verbose_name_plural': '物料动态变化',
                'db_table': 'inventory_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
