# Generated by Django 6.0.6 on 2026-06-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='record_type',
            field=models.CharField(choices=[('in', '入库'), ('out', '出库')], db_index=True, max_length=10, verbose_name='记录类型'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='名称必须规范、一致，直接影响下位机用料统计', max_length=128, verbose_name='物料名称'),
        ),
    ]
