# Generated by Django 6.0.6 on 2026-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryrecord_record_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='名称必须规范、一致，直接影响下位机用料统计', max_length=128, unique=True, verbose_name='物料名称'),
        ),
    ]
