# Generated by Django 6.0.6 on 2026-06-24 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_material_name'),
        ('stores', '0004_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='store',
            field=models.ForeignKey(blank=True, help_text='仅在“出库”时需要选择对应的门店', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_records', to='stores.store', verbose_name='出库目标门店'),
        ),
    ]
