# Generated by Django 6.0.6 on 2026-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryrecord_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('ingredient', '食材'), ('consumable', '耗材')], default='ingredient', max_length=20, verbose_name='物料类别'),
        ),
    ]
