# Generated by Django 6.0.6 on 2026-08-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_material_material_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='precautions',
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='入库时必填单价（元）', max_digits=10, null=True, verbose_name='单价/价格'),
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='单位单价（元）', max_digits=10, verbose_name='物料单价/售价'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('ingredient', '食材'), ('consumable', '耗材'), ('cup', '杯/耗材(cup)'), ('ice', '冰块(ice)'), ('thin', '稀液料(thin)'), ('thick', '稠液料(thick)'), ('solid', '固体料(solid)')], default='ingredient', max_length=20, verbose_name='物料类别'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(help_text='如：kg, 升, 包, 箱, 个, ml, g', max_length=32, verbose_name='计量单位'),
        ),
    ]
