# Generated by Django on 2026-08-21
from django.db import migrations


def seed_materials(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == 'mysql':
            cursor.execute("SET FOREIGN_KEY_CHECKS = 0;")

    Material = apps.get_model('inventory', 'Material')
    GlobalSkuIngredient = apps.get_model('global_config', 'GlobalSkuIngredient')

    materials_data = [
        {"code": "plasticL", "type": "cup", "name": "塑料大杯", "price": 30.0, "unit": "个"},
        {"code": "plasticM", "type": "cup", "name": "塑料中杯", "price": 22.0, "unit": "个"},
        {"code": "paperL", "type": "cup", "name": "纸大杯", "price": 40.0, "unit": "个"},
        {"code": "paperM", "type": "cup", "name": "纸中杯", "price": 28.0, "unit": "个"},
        {"code": "membrane", "type": "cup", "name": "膜", "price": 16.0, "unit": "张"},
        {"code": "lid", "type": "cup", "name": "盖", "price": 36.0, "unit": "个"},
        {"code": "ice", "type": "ice", "name": "冰块", "price": 1.5, "unit": "g"},
        {"code": "water", "type": "thin", "name": "水", "price": 1.0, "unit": "ml"},
        {"code": "sugar", "type": "thick", "name": "糖浆", "price": 2.0, "unit": "g"},
        {"code": "sweetener", "type": "thick", "name": "甜味剂", "price": 2.0, "unit": "g"},
        {"code": "YG", "type": "solid", "name": "椰果", "price": 3.0, "unit": "g"},
        {"code": "CBB", "type": "solid", "name": "脆啵啵", "price": 3.0, "unit": "g"},
        {"code": "iL01", "type": "thin", "name": "液料一", "price": 2.5, "unit": "ml"},
    ]

    for item in materials_data:
        mat_by_code = Material.objects.filter(code=item['code']).first()
        mat_by_name = Material.objects.filter(name=item['name']).first()

        if mat_by_code:
            old_name = mat_by_code.name
            new_name = item['name']
            if old_name != new_name:
                GlobalSkuIngredient.objects.filter(material_id=old_name).update(material_id=new_name)
                mat_by_code.name = new_name
            mat_by_code.material_type = item['type']
            mat_by_code.price = item['price']
            mat_by_code.unit = item['unit']
            mat_by_code.save()
        elif mat_by_name:
            mat_by_name.code = item['code']
            mat_by_name.material_type = item['type']
            mat_by_name.price = item['price']
            mat_by_name.unit = item['unit']
            mat_by_name.save()
        else:
            Material.objects.create(
                code=item['code'],
                name=item['name'],
                material_type=item['type'],
                price=item['price'],
                unit=item['unit'],
                shelf_life='常温/长期',
                storage_conditions='常温'
            )

    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == 'mysql':
            cursor.execute("SET FOREIGN_KEY_CHECKS = 1;")


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_material_precautions_inventoryrecord_price_and_more'),
        ('global_config', '0014_remove_globalskutemplate_attributes'),
    ]

    operations = [
        migrations.RunPython(seed_materials, reverse_seed),
    ]
