# Generated by Django 6.0.6 on 2026-08-23 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_alter_deviceposter_options_and_more'),
        ('inventory', '0008_alter_inventoryrecord_expiration_date'),
        ('stores', '0004_alter_store_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('in_from_warehouse', '总仓分拨入店'), ('out_to_device', '出库加料到设备')], db_index=True, max_length=32, verbose_name='流转类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='流转数量')),
                ('remarks', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='流转发生时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_refill_records', to='devices.device', verbose_name='目标设备')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_records', to='inventory.material', verbose_name='关联物料')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经办操作员')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory_records', to='stores.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '门店调拨流水',
                'verbose_name_plural': '门店调拨流水列表',
                'db_table': 'store_inventory_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='当前在店库存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后变动时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventories', to='inventory.material', verbose_name='关联物料')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventories', to='stores.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '门店物料库存',
                'verbose_name_plural': '门店物料库存列表',
                'db_table': 'store_inventory',
                'ordering': ['store', 'material'],
                'unique_together': {('store', 'material')},
            },
        ),
    ]
