# Generated by Django 6.0.6 on 2026-09-09 21:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_batch_tracking(apps, schema_editor):
    import uuid
    from django.utils import timezone
    InventoryRecord = apps.get_model('inventory', 'InventoryRecord')
    inbound_records = InventoryRecord.objects.filter(record_type='in')
    for rec in inbound_records:
        updated = False
        if not rec.batch_no:
            date_str = rec.created_at.strftime('%Y%m%d') if rec.created_at else timezone.now().strftime('%Y%m%d')
            rec.batch_no = f"BAT-{date_str}-{uuid.uuid4().hex[:6].upper()}"
            updated = True
        if rec.remaining_quantity is None or rec.remaining_quantity == Decimal('0.00'):
            rec.remaining_quantity = rec.quantity
            updated = True
        if updated:
            rec.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_storeinventoryrecord_storeinventory'),
        ('stores', '0004_alter_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='batch_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='批次编号'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='总仓批次剩余数量'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_allocations', to='inventory.inventoryrecord', verbose_name='来源入库批次'),
        ),
        migrations.AddField(
            model_name='storeinventoryrecord',
            name='batch_no',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='流转批次号'),
        ),
        migrations.AddField(
            model_name='storeinventoryrecord',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='批次成本单价'),
        ),
        migrations.AddField(
            model_name='storeinventoryrecord',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='批次过期时间'),
        ),
        migrations.CreateModel(
            name='StoreInventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(db_index=True, max_length=64, verbose_name='批次编号')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='在店批次库存')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='批次采购进价')),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='批次过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入店时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后变动时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_batches', to='inventory.material', verbose_name='关联物料')),
                ('source_inbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryrecord', verbose_name='来源总仓入库记录')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stores.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '门店物料批次库存',
                'verbose_name_plural': '门店物料批次库存列表',
                'db_table': 'store_inventory_batch',
                'ordering': ['expiration_date', 'created_at'],
                'unique_together': {('store', 'material', 'batch_no')},
            },
        ),
        migrations.RunPython(backfill_batch_tracking, reverse_code=migrations.RunPython.noop),
    ]
