# Generated by Django 6.0.6 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_batch_tracking_and_fefo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='expiration_date',
            field=models.DateField(blank=True, db_index=True, help_text='进货/入库时若留空，cup类默认3年，其他物料默认6个月', null=True, verbose_name='批次过期时间'),
        ),
    ]
