version = 5.6.0
archive_dir = /etc/letsencrypt/archive/tinylab.store
cert = /etc/letsencrypt/live/tinylab.store/cert.pem
privkey = /etc/letsencrypt/live/tinylab.store/privkey.pem
chain = /etc/letsencrypt/live/tinylab.store/chain.pem
fullchain = /etc/letsencrypt/live/tinylab.store/fullchain.pem
[renewalparams]
account = bd313c445abbbf51e875704bf68e1a3a
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
tinylab.store = /var/www/html
