# Generated by Django 6.0.6 on 2026-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMonitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sn', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='设备序列号')),
                ('healthy', models.BooleanField(default=True, verbose_name='整机健康')),
                ('disconnected', models.BooleanField(default=False, verbose_name='是否断线')),
                ('last_time', models.BigIntegerField(default=0, verbose_name='上报时间戳(ms)')),
                ('mem_size', models.JSONField(blank=True, default=dict, verbose_name='内存信息')),
                ('abnormality', models.JSONField(blank=True, default=dict, verbose_name='异常详情')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始上报数据')),
                ('reported_at', models.DateTimeField(auto_now=True, verbose_name='最后上报时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次上报时间')),
            ],
            options={
                'verbose_name': '设备监控快照',
                'verbose_name_plural': '设备监控快照列表',
                'db_table': 'device_monitor_snapshot',
                'ordering': ['device_sn'],
            },
        ),
    ]
