# Generated by Django 6.0.6 on 2026-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemonitorsnapshot',
            name='device_sn',
            field=models.CharField(db_index=True, max_length=128, verbose_name='设备序列号'),
        ),
    ]
