# Generated by Django 6.0.6 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_devicemonitorsnapshot_device_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemonitorsnapshot',
            name='device_sn',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='设备序列号'),
        ),
    ]
