# Generated by Django 6.0.6 on 2026-06-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='设备类型名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='类型编码')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局设备类型',
                'verbose_name_plural': '全局设备类型列表',
                'db_table': 'global_device_type',
            },
        ),
        migrations.CreateModel(
            name='GlobalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='物料名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='物料编码')),
                ('unit', models.CharField(default='ml', max_length=16, verbose_name='标准单位')),
                ('description', models.TextField(blank=True, verbose_name='物料描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局物料',
                'verbose_name_plural': '全局物料列表',
                'db_table': 'global_material',
            },
        ),
        migrations.CreateModel(
            name='GlobalMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('icon_url', models.FileField(blank=True, max_length=512, upload_to='global_category_icons/', verbose_name='分类图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='global_config.devicetype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '全局菜单分类',
                'verbose_name_plural': '全局菜单分类列表',
                'db_table': 'global_menu_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('image_url', models.URLField(blank=True, max_length=512, verbose_name='商品图片')),
                ('base_price', models.IntegerField(default=0, verbose_name='基础价格（分）')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='global_config.globalmenucategory', verbose_name='全局分类')),
            ],
            options={
                'verbose_name': '全局菜单商品',
                'verbose_name_plural': '全局菜单商品列表',
                'db_table': 'global_menu_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalMenuSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='规格名称')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='规格属性')),
                ('price_delta', models.IntegerField(default=0, verbose_name='价格增量（分）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='global_config.globalmenuitem', verbose_name='全局商品')),
            ],
            options={
                'verbose_name': '全局商品规格',
                'verbose_name_plural': '全局商品规格列表',
                'db_table': 'global_menu_sku',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSkuIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='用量')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='单位(留空使用物料默认单位)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='global_config.globalmaterial', verbose_name='物料')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='global_config.globalmenusku', verbose_name='全局规格(SKU)')),
            ],
            options={
                'verbose_name': '全局规格配料',
                'verbose_name_plural': '全局规格配料列表',
                'db_table': 'global_sku_ingredient',
            },
        ),
    ]
