# Generated by Django 6.0.6 on 2026-06-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmenusku',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='分类'),
        ),
    ]
