# Generated by Django 6.0.6 on 2026-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0002_globalmenusku_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmaterial',
            name='deviceSN',
            field=models.CharField(default='1', max_length=128, verbose_name='设备编号'),
        ),
        migrations.AddField(
            model_name='globalmaterial',
            name='deviceVersion',
            field=models.CharField(default='1', max_length=128, verbose_name='设备版本'),
        ),
        migrations.AddField(
            model_name='globalmaterial',
            name='initHight',
            field=models.IntegerField(default=10, verbose_name='满料高度'),
        ),
        migrations.AlterField(
            model_name='globalmaterial',
            name='unit',
            field=models.CharField(default='cm', max_length=16, verbose_name='标准单位'),
        ),
    ]
