# Generated by Django 6.0.6 on 2026-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0003_globalmaterial_devicesn_globalmaterial_deviceversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='耗材编号')),
                ('name', models.CharField(max_length=128, verbose_name='耗材名称')),
                ('initQuantity', models.IntegerField(default=0, verbose_name='初始化数量')),
                ('deviceSN', models.CharField(default='1', max_length=128, verbose_name='设备编号')),
                ('description', models.TextField(blank=True, verbose_name='耗材描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局包装耗材',
                'verbose_name_plural': '全局包装耗材列表',
                'db_table': 'global_consumable',
            },
        ),
    ]
