# Generated by Django 6.0.6 on 2026-06-22 18:32

import global_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0004_globalconsumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmenuitem',
            name='detail_page',
            field=models.FileField(blank=True, null=True, upload_to='menu_details/', validators=[global_config.models.validate_detail_image], verbose_name='商品详情页图'),
        ),
        migrations.AddField(
            model_name='globalmenuitem',
            name='main_ingredients',
            field=models.CharField(blank=True, max_length=256, verbose_name='主要原料'),
        ),
        migrations.AddField(
            model_name='globalmenuitem',
            name='price_description',
            field=models.CharField(blank=True, max_length=256, verbose_name='价格说明'),
        ),
    ]
