# Generated by Django 6.0.6 on 2026-06-23 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0006_rename_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalskuingredient',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='global_config.globalmaterial', verbose_name='物料'),
        ),
    ]
