# Generated by Django 6.0.6 on 2026-06-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0009_remove_globalmaterial_devicesn_and_more'),
        ('inventory', '0003_alter_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalskuingredient',
            name='material',
            field=models.ForeignKey(db_column='material_name', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.material', to_field='name', verbose_name='物料'),
        ),
        migrations.DeleteModel(
            name='GlobalMaterial',
        ),
    ]
