# Generated by Django 6.0.6 on 2026-06-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0010_alter_globalskuingredient_material_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalConsumable',
        ),
    ]
