# Generated by Django 6.0.6 on 2026-07-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0011_delete_globalconsumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmenucategory',
            name='label',
            field=models.CharField(default='recomm', max_length=64, verbose_name='分类标签'),
        ),
    ]
