# Generated by Django on 2026-08-21
import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_skus_to_templates(apps, schema_editor):
    GlobalMenuSku = apps.get_model('global_config', 'GlobalMenuSku')
    GlobalSkuTemplate = apps.get_model('global_config', 'GlobalSkuTemplate')
    
    template_map = {}
    for sku in GlobalMenuSku.objects.all():
        name = getattr(sku, 'name', '') or '默认规格'
        category = getattr(sku, 'category', '') or '通用'
        attributes = getattr(sku, 'attributes', {}) or {}
        price_delta = getattr(sku, 'price_delta', 0) or 0
        
        key = (name, category)
        if key not in template_map:
            tpl, _ = GlobalSkuTemplate.objects.get_or_create(
                name=name,
                category=category,
                defaults={
                    'default_price_delta': price_delta,
                    'attributes': attributes,
                    'is_active': True,
                    'sort_order': getattr(sku, 'sort_order', 0)
                }
            )
            template_map[key] = tpl
        
        sku.template = template_map[key]
        sku.save(update_fields=['template'])


def reverse_migration(apps, schema_editor):
    GlobalMenuSku = apps.get_model('global_config', 'GlobalMenuSku')
    for sku in GlobalMenuSku.objects.select_related('template').all():
        if sku.template:
            sku.name = sku.template.name
            sku.category = sku.template.category
            sku.attributes = sku.template.attributes
            sku.save(update_fields=['name', 'category', 'attributes'])


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0012_globalmenucategory_label'),
        ('inventory', '0003_alter_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSkuTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='例如：杯型、温度、糖度、通用等', max_length=64, verbose_name='规格分类')),
                ('name', models.CharField(help_text='例如：标准、大杯、热、去冰、五分糖等', max_length=128, verbose_name='规格名称')),
                ('default_price_delta', models.IntegerField(default=0, verbose_name='默认价格增量（分）')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='规格属性')),
                ('description', models.TextField(blank=True, verbose_name='规格描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局规格模板',
                'verbose_name_plural': '全局规格模板列表',
                'db_table': 'global_sku_template',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSkuTemplateIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='默认用量')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='单位(留空使用物料默认单位)')),
                ('material', models.ForeignKey(db_column='material_name', on_delete=django.db.models.deletion.CASCADE, related_name='template_ingredients', to='inventory.material', to_field='name', verbose_name='物料')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='global_config.globalskutemplate', verbose_name='规格模板')),
            ],
            options={
                'verbose_name': '全局规格模板配料',
                'verbose_name_plural': '全局规格模板配料列表',
                'db_table': 'global_sku_template_ingredient',
            },
        ),
        migrations.AddField(
            model_name='globalmenusku',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_skus', to='global_config.globalskutemplate', verbose_name='规格模板'),
        ),
        migrations.RunPython(
            migrate_existing_skus_to_templates,
            reverse_migration
        ),
        migrations.AlterField(
            model_name='globalmenusku',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_skus', to='global_config.globalskutemplate', verbose_name='规格模板'),
        ),
        migrations.RemoveField(
            model_name='globalmenusku',
            name='name',
        ),
        migrations.RemoveField(
            model_name='globalmenusku',
            name='category',
        ),
        migrations.RemoveField(
            model_name='globalmenusku',
            name='attributes',
        ),
        migrations.AlterUniqueTogether(
            name='globalmenusku',
            unique_together={('item', 'template')},
        ),
    ]
