# Generated by Django 6.0.6 on 2026-08-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_config', '0013_globalskutemplate_and_sku_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalskutemplate',
            name='attributes',
        ),
    ]
