# Generated by Django 6.0.6 on 2026-06-09 04:27

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('menus', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('operator', models.CharField(blank=True, max_length=64, verbose_name='操作方')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '订单状态日志',
                'verbose_name_plural': '订单状态日志',
                'db_table': 'order_status_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待下发'), ('sent', '已下发'), ('making', '制作中'), ('done', '制作完成'), ('failed', '制作失败')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('command_payload', models.JSONField(default=dict, verbose_name='命令数据')),
                ('failure_reason', models.CharField(blank=True, max_length=256, verbose_name='失败原因')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='下发时间')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生产任务',
                'verbose_name_plural': '生产任务列表',
                'db_table': 'production_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=128, verbose_name='商品名称快照')),
                ('sku_name', models.CharField(blank=True, max_length=64, verbose_name='规格名称快照')),
                ('unit_price', models.IntegerField(verbose_name='单价（分）')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('subtotal', models.IntegerField(verbose_name='小计（分）')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menus.menuitem', verbose_name='商品')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menus.menusku', verbose_name='规格')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细列表',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, default=orders.models.generate_order_no, max_length=32, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending_pay', '待支付'), ('paid', '已支付'), ('making', '制作中'), ('done', '已完成'), ('cancelled', '已取消'), ('refunding', '退款中'), ('refunded', '已退款'), ('exception', '异常')], db_index=True, default='pending_pay', max_length=20, verbose_name='订单状态')),
                ('total_amount', models.IntegerField(default=0, verbose_name='总金额（分）')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='优惠金额（分）')),
                ('pay_amount', models.IntegerField(default=0, verbose_name='实付金额（分）')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='devices.device', verbose_name='制作设备')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store', verbose_name='下单门店')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单列表',
                'db_table': 'order_main',
                'ordering': ['-created_at'],
            },
        ),
    ]
