# Generated by Django 6.0.6 on 2026-06-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_menusku'),
        ('orders', '0003_alter_orderitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menus.menusku', verbose_name='规格'),
        ),
    ]
