# Generated by Django 6.0.6 on 2026-06-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_remove_menusku_category'),
        ('orders', '0004_alter_orderitem_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='skus',
            field=models.ManyToManyField(blank=True, related_name='order_item_list', to='menus.menusku', verbose_name='规格列表'),
        ),
        migrations.AddField(
            model_name='ordermain',
            name='order_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='订单Token'),
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='status',
            field=models.CharField(choices=[('created', '已创建'), ('pending_dispense', '待出货'), ('making', '制作中'), ('success', '已完成'), ('cancelled', '已取消'), ('refunding', '退款中'), ('refunded', '已退款'), ('failed', '已失败')], db_index=True, default='created', max_length=20, verbose_name='订单状态'),
        ),
    ]
