# Generated by Django 6.0.6 on 2026-06-23 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_remove_menusku_category'),
        ('orders', '0005_orderitem_skus_ordermain_order_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menus.menuitem', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menus.menusku', verbose_name='规格'),
        ),
    ]
