# Generated by Django 6.0.6 on 2026-08-23 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_item_alter_orderitem_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('personal', '个人/非企业单位'), ('company', '企业单位')], default='personal', max_length=20, verbose_name='发票类型')),
                ('title', models.CharField(max_length=128, verbose_name='发票抬头')),
                ('tax_no', models.CharField(blank=True, default='', max_length=64, verbose_name='企业税号')),
                ('email', models.EmailField(max_length=254, verbose_name='接收邮箱')),
                ('amount', models.IntegerField(verbose_name='开票金额（分）')),
                ('status', models.CharField(choices=[('submitted', '已申请'), ('issued', '已开具'), ('failed', '开票失败')], default='issued', max_length=20, verbose_name='开票状态')),
                ('invoice_url', models.URLField(blank=True, default='', max_length=512, verbose_name='电子发票下载链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.ordermain', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '电子发票',
                'verbose_name_plural': '电子发票列表',
                'db_table': 'order_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='优惠券名称')),
                ('coupon_type', models.CharField(choices=[('reduction', '满减券'), ('direct', '无门槛立减券'), ('discount', '折扣券')], default='direct', max_length=20, verbose_name='优惠类型')),
                ('amount', models.IntegerField(default=500, verbose_name='面额（分）')),
                ('min_spend', models.IntegerField(default=0, verbose_name='使用门槛（分）')),
                ('discount_rate', models.IntegerField(default=100, verbose_name='折扣率(%)')),
                ('status', models.CharField(choices=[('available', '可使用'), ('used', '已使用'), ('expired', '已过期')], db_index=True, default='available', max_length=20, verbose_name='状态')),
                ('expires_at', models.DateTimeField(verbose_name='有效期至')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('used_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='orders.ordermain', verbose_name='核销订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券列表',
                'db_table': 'user_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='积分变动(正加负减)')),
                ('balance_after', models.IntegerField(default=0, verbose_name='变动后积分余额')),
                ('action', models.CharField(max_length=128, verbose_name='变动说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_logs', to='orders.ordermain', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水列表',
                'db_table': 'user_point_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
