# Generated by Django 6.0.6 on 2026-09-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderstatuslog_action_orderstatuslog_action_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='stock_deducted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='耗材库存是否已扣减'),
        ),
    ]
