# Generated by Django 6.0.6 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordermain_stock_deducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpointlog',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userpointlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='status',
            field=models.CharField(choices=[('submitted', '已申请'), ('issued', '已开具'), ('failed', '开票失败')], db_index=True, default='issued', max_length=20, verbose_name='开票状态'),
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
        migrations.DeleteModel(
            name='UserPointLog',
        ),
    ]
