# Generated by Django 6.0.6 on 2026-06-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='原始上报数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '设备状态日志',
                'verbose_name_plural': '设备状态日志',
                'db_table': 'device_status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sn', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='设备序列号')),
                ('device_name', models.CharField(blank=True, max_length=128, verbose_name='设备名称')),
                ('device_model', models.CharField(blank=True, max_length=64, verbose_name='设备型号')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('fault', '故障')], db_index=True, default='offline', max_length=20, verbose_name='设备状态')),
                ('firmware_version', models.CharField(blank=True, max_length=64, verbose_name='固件版本')),
                ('resource_version', models.IntegerField(default=0, verbose_name='资源版本号')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('mqtt_topic_prefix', models.CharField(blank=True, max_length=256, verbose_name='MQTT Topic 前缀')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='stores.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备列表',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DeviceAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('fault', '设备故障'), ('low_material', '物料不足'), ('offline', '设备离线')], max_length=32, verbose_name='告警类型')),
                ('detail', models.TextField(blank=True, verbose_name='告警详情')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='是否已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备告警',
                'verbose_name_plural': '设备告警列表',
                'db_table': 'device_alarm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('make', '制作命令'), ('cancel', '取消命令'), ('reset', '复位命令'), ('sync_resource', '资源同步')], max_length=32, verbose_name='命令类型')),
                ('payload', models.JSONField(default=dict, verbose_name='命令内容')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('confirmed', '已确认'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='发送状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device', verbose_name='目标设备')),
            ],
            options={
                'verbose_name': '设备命令',
                'verbose_name_plural': '设备命令列表',
                'db_table': 'device_command',
                'ordering': ['-created_at'],
            },
        ),
    ]
