# Generated by Django 6.0.6 on 2026-06-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommand',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_commands', to='orders.ordermain', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='devicestatuslog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='devices.device', verbose_name='设备'),
        ),
    ]
