# Generated by Django 6.0.6 on 2026-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='key_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='门店注册码'),
        ),
    ]
