# Generated by Django 6.0.6 on 2026-06-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_key_code'),
        ('global_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='global_config.devicetype', verbose_name='设备类型'),
        ),
    ]
