# Generated by Django 6.0.6 on 2026-06-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(db_index=True, max_length=64, verbose_name='物料编码')),
                ('material_name', models.CharField(blank=True, max_length=64, verbose_name='物料名称')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='账面库存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_stocks', to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备物料库存',
                'verbose_name_plural': '设备物料库存列表',
                'db_table': 'device_material_stock',
                'unique_together': {('device', 'material_code')},
            },
        ),
    ]
