# Generated by Django 6.0.6 on 2026-06-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_rename_device_type_to_device_model'),
        ('inventory', '0003_alter_material_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicematerialstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devicematerialstock',
            name='code',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='物料编码'),
        ),
        migrations.AddField(
            model_name='devicematerialstock',
            name='initHight',
            field=models.IntegerField(default=100, verbose_name='满料高度'),
        ),
        migrations.AddField(
            model_name='devicematerialstock',
            name='name',
            field=models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.material', to_field='name', verbose_name='物料名称'),
        ),
        migrations.AddField(
            model_name='devicematerialstock',
            name='unit',
            field=models.CharField(default='cm', max_length=16, verbose_name='标准单位'),
        ),
        migrations.AddField(
            model_name='devicematerialstock',
            name='warn_level',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='预警高度'),
        ),
        migrations.RemoveField(
            model_name='devicematerialstock',
            name='material_code',
        ),
        migrations.RemoveField(
            model_name='devicematerialstock',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='devicematerialstock',
            name='quantity',
        ),
        migrations.AlterUniqueTogether(
            name='devicematerialstock',
            unique_together={('device', 'code')},
        ),
    ]
