# Generated by Django 6.0.6 on 2026-06-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_devicematerialstock_unique_together_and_more'),
        ('inventory', '0003_alter_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicematerialstock',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='devicematerialstock',
            name='name',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='inventory.material', to_field='name', verbose_name='物料名称'),
        ),
    ]
