# Generated by Django 6.0.6 on 2026-06-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_devicematerialstock_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicematerialstock',
            name='warn_level',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='预警高度'),
        ),
    ]
