# Generated by Django 6.0.6 on 2026-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_devicematerialstock_warn_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicematerialstock',
            name='current_remaining_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='当前剩余高度'),
        ),
        migrations.AddField(
            model_name='devicematerialstock',
            name='warn_level_1',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='预警高度1'),
        ),
        migrations.AddField(
            model_name='devicematerialstock',
            name='warn_level_2',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='预警高度2'),
        ),
        migrations.AddField(
            model_name='devicematerialstock',
            name='warn_level_3',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10, verbose_name='预警高度3'),
        ),
    ]
