# Generated by Django 6.0.6 on 2026-06-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_devicematerialstock_current_remaining_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConsumableStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('paperL', '大号纸杯'), ('paperM', '中号纸杯'), ('plasticL', '大号塑料杯'), ('plasticM', '中号塑料杯'), ('membrane', '封口膜'), ('lid', '杯盖')], max_length=64, verbose_name='耗材编码')),
                ('name', models.CharField(max_length=128, verbose_name='耗材名称')),
                ('init_quantity', models.IntegerField(default=100, verbose_name='满载数量')),
                ('quantity', models.IntegerField(default=100, verbose_name='当前剩余数量')),
                ('unit', models.CharField(default='个', max_length=16, verbose_name='标准单位')),
                ('warn_level', models.IntegerField(default=20, verbose_name='预警数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_stocks', to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备耗材库存',
                'verbose_name_plural': '设备耗材库存列表',
                'db_table': 'device_consumable_stock',
                'unique_together': {('device', 'code')},
            },
        ),
    ]
