# Generated by Django 6.0.6 on 2026-06-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_deviceconsumablestock'),
        ('inventory', '0005_material_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconsumablestock',
            name='name',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='inventory.material', to_field='name', verbose_name='耗材名称'),
        ),
    ]
