# Generated by Django 6.0.6 on 2026-06-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_deviceconsumablestock_name'),
        ('inventory', '0005_material_material_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconsumablestock',
            name='name',
        ),
        migrations.AlterField(
            model_name='deviceconsumablestock',
            name='code',
            field=models.ForeignKey(choices=[('paperL', '大号纸杯'), ('paperM', '中号纸杯'), ('plasticL', '大号塑料杯'), ('plasticM', '中号塑料杯'), ('membrane', '封口膜'), ('lid', '杯盖')], db_column='code', on_delete=django.db.models.deletion.CASCADE, to='inventory.material', to_field='code', verbose_name='耗材编码'),
        ),
    ]
