# Generated by Django 6.0.6 on 2026-06-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_alter_deviceconsumablestock_code'),
        ('inventory', '0005_material_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconsumablestock',
            name='code',
            field=models.ForeignKey(db_column='code', limit_choices_to={'material_type': 'consumable'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.material', to_field='code', verbose_name='耗材编码'),
        ),
    ]
