# Generated by Django 6.0.6 on 2026-07-10 20:59

import devices.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_alter_deviceconsumablestock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconsumablestock',
            name='warn_level',
            field=models.IntegerField(default=10, verbose_name='预警数量'),
        ),
        migrations.AlterField(
            model_name='devicematerialstock',
            name='warn_level',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='预警高度'),
        ),
        migrations.AlterField(
            model_name='devicematerialstock',
            name='warn_level_2',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=20, verbose_name='预警高度2'),
        ),
        migrations.AlterField(
            model_name='devicematerialstock',
            name='warn_level_3',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=30, verbose_name='预警高度3'),
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.JSONField(default=devices.models.default_temperature_config, verbose_name='温度配置(摄氏度)')),
                ('transfer', models.JSONField(default=devices.models.default_transfer_config, verbose_name='转运模块配置(坐标值)')),
                ('barrel', models.JSONField(default=devices.models.default_barrel_config, verbose_name='桶配置')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='devices.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '设备配置',
                'verbose_name_plural': '设备配置列表',
                'db_table': 'device_config',
            },
        ),
    ]
