# Generated by Django 6.0.6 on 2026-07-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_deviceconsumablestock_warn_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceconfig',
            options={'verbose_name': '设备全局配置', 'verbose_name_plural': '设备全局配置列表'},
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='barrel',
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='transfer',
            field=models.CharField(default='10000,20000,30000,40000,50000,60000,70000,80000,90000,100000,110000,120000,130000,140000', max_length=512, verbose_name='转运模块配置(坐标值,用逗号分隔)'),
        ),
        migrations.CreateModel(
            name='DeviceBarrel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrel_id', models.CharField(max_length=32, verbose_name='料筒编号(例如 b01)')),
                ('pump_type', models.CharField(default='thin', max_length=32, verbose_name='泵类型')),
                ('pump_coeff', models.IntegerField(default=100, verbose_name='泵系数')),
                ('max_v', models.IntegerField(default=40000, verbose_name='最大容量')),
                ('base_area', models.IntegerField(default=800, verbose_name='底面积(cm²)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrels', to='devices.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '设备料筒项',
                'verbose_name_plural': '设备料筒项列表',
                'db_table': 'device_barrel_config',
                'unique_together': {('device', 'barrel_id')},
            },
        ),
        migrations.CreateModel(
            name='DeviceTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, verbose_name='温度标识(例如 t1)')),
                ('value', models.IntegerField(verbose_name='设定温度(摄氏度)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='devices.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '设备温度项',
                'verbose_name_plural': '设备温度项列表',
                'db_table': 'device_temperature_config',
                'unique_together': {('device', 'key')},
            },
        ),
    ]
