# Generated by Django 6.0.6 on 2026-07-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_alter_deviceconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicetemperature',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devicebarrel',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barrels', to='devices.deviceconfig', verbose_name='所属配置'),
        ),
        migrations.AddField(
            model_name='devicetemperature',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='devices.deviceconfig', verbose_name='所属配置'),
        ),
        migrations.AlterField(
            model_name='devicebarrel',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barrels', to='devices.device', verbose_name='所属设备(冗余)'),
        ),
        migrations.AlterField(
            model_name='devicetemperature',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='devices.device', verbose_name='所属设备(冗余)'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetemperature',
            unique_together={('config', 'key')},
        ),
    ]
