# Generated by Django 6.0.6 on 2026-07-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_devicetemperature_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSoftConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_vacancies', models.IntegerField(default=3, verbose_name='出餐口数量(maxVacancies)')),
                ('sep_chunk', models.IntegerField(default=2, verbose_name='分单块大小(sepChunk)')),
                ('ice_size', models.IntegerField(default=15, verbose_name='冰块大小(iceSize, ml)')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soft_conf', to='devices.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '设备出餐配置',
                'verbose_name_plural': '设备出餐配置列表',
                'db_table': 'device_soft_conf',
            },
        ),
        migrations.CreateModel(
            name='DeviceCupSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, verbose_name='杯型标识(例如 m/l)')),
                ('capacity', models.IntegerField(verbose_name='容量(ml)')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup_sizes', to='devices.device', verbose_name='所属设备(冗余)')),
                ('soft_conf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup_sizes', to='devices.devicesoftconf', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '设备杯型容量',
                'verbose_name_plural': '设备杯型容量列表',
                'db_table': 'device_cup_size_config',
                'unique_together': {('soft_conf', 'key')},
            },
        ),
    ]
