# Generated by Django 6.0.6 on 2026-08-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_devicesoftconf_devicecupsize'),
        ('inventory', '0006_remove_material_precautions_inventoryrecord_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconsumablestock',
            name='code',
            field=models.ForeignKey(db_column='code', limit_choices_to={'material_type__in': ['consumable', 'cup']}, on_delete=django.db.models.deletion.CASCADE, to='inventory.material', to_field='code', verbose_name='耗材编码'),
        ),
    ]
