# Generated by Django 6.0.6 on 2026-08-21 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_deviceconsumablestock_code'),
        ('inventory', '0008_alter_inventoryrecord_expiration_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBarrelDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrel_code', models.CharField(db_index=True, help_text='例如：b01, b02, b09 等', max_length=64, verbose_name='桶编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_barrel_dicts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('device', models.ForeignKey(db_column='device_sn', on_delete=django.db.models.deletion.CASCADE, related_name='barrel_dicts', to='devices.device', to_field='device_sn', verbose_name='设备编号')),
                ('material', models.ForeignKey(db_column='material_code', on_delete=django.db.models.deletion.CASCADE, related_name='barrel_dicts', to='inventory.material', to_field='code', verbose_name='物料编号')),
            ],
            options={
                'verbose_name': '料桶字典',
                'verbose_name_plural': '料桶字典列表',
                'db_table': 'device_barrel_dict',
                'ordering': ['device', 'barrel_code'],
                'unique_together': {('device', 'barrel_code')},
            },
        ),
    ]
