# Generated by Django 6.0.6 on 2026-08-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_devicebarreldict'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='设备地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='gps_coordinate',
            field=models.CharField(blank=True, default='', help_text='例如：116.4074,39.9042', max_length=128, verbose_name='设备GPS坐标'),
        ),
    ]
