# Generated by Django 6.0.6 on 2026-08-21 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_device_address_device_gps_coordinate'),
        ('stores', '0004_alter_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='例如：开业大酬宾、夏日特饮等', max_length=128, verbose_name='海报标题')),
                ('poster_type', models.CharField(choices=[('horizontal', '横屏海报 (horizontal)'), ('vertical', '竖屏海报 (vertical)'), ('banner', '横幅海报 (banner)')], db_index=True, default='horizontal', max_length=32, verbose_name='海报类型')),
                ('image', models.ImageField(upload_to='posters/%Y/%m/', verbose_name='海报图片')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小越靠前', verbose_name='排序权重')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('version', models.CharField(blank=True, default='0.0.0', max_length=32, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(blank=True, help_text='留空则对该门店或全局生效', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='devices.device', verbose_name='指定设备')),
                ('store', models.ForeignKey(blank=True, help_text='留空则对所有设备全局生效', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='stores.store', verbose_name='指定门店')),
            ],
            options={
                'verbose_name': '设备海报',
                'verbose_name_plural': '设备海报列表',
                'db_table': 'device_poster',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
