# Generated by Django 6.0.6 on 2026-08-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_deviceposter'),
        ('stores', '0004_alter_store_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceposter',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '设备海报', 'verbose_name_plural': '设备海报列表'},
        ),
        migrations.RemoveField(
            model_name='deviceposter',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceposter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='deviceposter',
            name='poster_type',
        ),
        migrations.RemoveField(
            model_name='deviceposter',
            name='store',
        ),
        migrations.AddField(
            model_name='deviceposter',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='上传Banner横幅图片', null=True, upload_to='posters/banner/%Y/%m/', verbose_name='横幅海报 (banner)'),
        ),
        migrations.AddField(
            model_name='deviceposter',
            name='devices',
            field=models.ManyToManyField(blank=True, help_text='可多选适用设备', related_name='posters', to='devices.device', verbose_name='指定设备 (多选)'),
        ),
        migrations.AddField(
            model_name='deviceposter',
            name='horizontal_image',
            field=models.ImageField(blank=True, help_text='上传横屏海报图片', null=True, upload_to='posters/horizontal/%Y/%m/', verbose_name='横屏海报 (horizontal)'),
        ),
        migrations.AddField(
            model_name='deviceposter',
            name='stores',
            field=models.ManyToManyField(blank=True, help_text='可多选适用门店；若不选门店且不选设备，则全局生效', related_name='posters', to='stores.store', verbose_name='指定门店 (多选)'),
        ),
        migrations.AddField(
            model_name='deviceposter',
            name='vertical_image',
            field=models.ImageField(blank=True, help_text='上传竖屏海报图片', null=True, upload_to='posters/vertical/%Y/%m/', verbose_name='竖屏海报 (vertical)'),
        ),
        migrations.AlterField(
            model_name='deviceposter',
            name='title',
            field=models.CharField(blank=True, help_text='例如：秋季新品推广、默认轮播海报等', max_length=128, verbose_name='海报配置名称'),
        ),
    ]
