# Generated by Django 6.0.6 on 2026-08-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_alter_deviceposter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceposter',
            name='remarks',
            field=models.CharField(blank=True, default='', help_text='例如：秋季开业海报、中秋限定海报等', max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='deviceposter',
            name='version',
            field=models.CharField(help_text='海报配置版本号，全局唯一（一个版本对应一组海报），例如：1.0.0, 1.0.1', max_length=32, unique=True, verbose_name='版本号'),
        ),
    ]
