# Generated by Django 6.0.6 on 2026-08-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_deviceposter_remarks_alter_deviceposter_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceposter',
            options={'ordering': ['-version', 'sort_order', '-created_at'], 'verbose_name': '设备海报', 'verbose_name_plural': '设备海报列表'},
        ),
        migrations.AlterField(
            model_name='deviceposter',
            name='version',
            field=models.IntegerField(blank=True, help_text='整数版本号（唯一），留空时系统自动在当前最大版本基础上+1', null=True, unique=True, verbose_name='版本号'),
        ),
    ]
