# Generated by Django 6.0.6 on 2026-08-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_alter_deviceposter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='device',
            name='province',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='省份'),
        ),
    ]
