# Generated by Django 6.0.6 on 2026-08-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_device_city_device_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='device',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度'),
        ),
    ]
