# Generated by Django 6.0.6 on 2026-08-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_device_lat_device_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConf1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sn', models.CharField(db_index=True, max_length=128, verbose_name='设备编号')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置内容 (JSON)')),
                ('version', models.CharField(default='1.0.0', help_text='配置版本号，如 1.0.0 或 20260830', max_length=64, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备配置1',
                'verbose_name_plural': '设备配置1列表',
                'db_table': 'device_conf1',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('make', '制作命令'), ('cancel', '取消命令'), ('reset', '复位命令'), ('sync_resource', '资源同步'), ('empty', '缺货通知')], max_length=32, verbose_name='命令类型'),
        ),
    ]
