# Generated by Django 6.0.6 on 2026-09-10 18:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_deviceconf1_alter_devicecommand_command_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebarreldict',
            name='alarm_threshold_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='达到或低于此值时发送报警短信并通知管理员(ml/g)', max_digits=10, verbose_name='报警1阈值'),
        ),
        migrations.AddField(
            model_name='devicebarreldict',
            name='alarm_threshold_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='达到或低于此值时该料桶可用物料=0，停止售卖(ml/g)', max_digits=10, verbose_name='报警2阈值(停售阈值)'),
        ),
        migrations.AddField(
            model_name='deviceconsumablestock',
            name='stop_sale_level',
            field=models.IntegerField(default=5, help_text='少于此数量时停止售卖(默认5个)', verbose_name='停售数量(报警2)'),
        ),
        migrations.AlterField(
            model_name='deviceconsumablestock',
            name='warn_level',
            field=models.IntegerField(default=20, help_text='少于此数量时报警(默认20个)', verbose_name='预警数量(报警1)'),
        ),
    ]
